  // ---- Inventory Presets ----
  const GEAR_PRESETS = {
    // Standard Issue
    rucksack:       { name: "Main Rucksack",               qty: 1, weight: "3.0 kg",  notes: "Standard Issue, ALICE, high-capacity ~70 L" },
    daypack:        { name: "Day Pack",                    qty: 1, weight: "0.8 kg",  notes: "Standard Issue, ~20 L" },
    sleepbag_light: { name: "Light Sleeping Bag",          qty: 1, weight: "1.2 kg",  notes: "Standard Issue, Plus-Temperaturen, ~-5 C" },
    sleepbag_heavy: { name: "Heavy Sleeping Bag",          qty: 1, weight: "2.4 kg",  notes: "Standard Issue, Winter/Arktis, ~-20 C" },
    lbs_vest:       { name: "Load-Bearing Vest",           qty: 1, weight: "",       notes: "Tool-Proficiency (Rifleman)" },
    camelbak:       { name: "CamelBak 2L",                 qty: 1, weight: "2.1 kg",  notes: "Wasser-Blase, 2 L full" },
    isomat:         { name: "Iso-mat",                     qty: 1, weight: "0.6 kg",  notes: "Isolierte Schlaf-Unterlage" },
    tarp:           { name: "Camo Tarpaulin 10x10 ft",     qty: 1, weight: "1.0 kg",  notes: "Tarnung / Shelter" },
    paracord:       { name: "100 ft Paracord (550)",       qty: 1, weight: "0.4 kg",  notes: "Reissfest bis 250 kg" },
    canteen:        { name: "Canteen 1L",                  qty: 4, weight: "1.0 kg",  notes: "Standard 4 pro Operator" },
    canteen_cup:    { name: "Canteen Cup",                 qty: 1, weight: "0.2 kg",  notes: "Metall-Trinkbecher" },
    messkit:        { name: "Mess Kit",                    qty: 1, weight: "0.5 kg",  notes: "Kochgeschirr, Field-Mess-Proficiency" },
    combat_knife:   { name: "Combat Knife",                qty: 1, weight: "0.4 kg",  notes: "Melee 1d4 Slashing, CQC" },
    bayonet:        { name: "Bayonet",                     qty: 1, weight: "0.5 kg",  notes: "An Rifle montiert, 1d4 Piercing" },

    // Class Tools
    ghillie:        { name: "Ghillie Suit",                qty: 1, weight: "",       notes: "Marksman: +5 Stealth (+10 mit Stalker), >1000ft invisible" },
    spotscope:      { name: "Spotting Scope",              qty: 1, weight: "2.0 kg",  notes: "Marksman Tool-Proficiency, Leupold Mk4 12-40x60" },
    te_tool:        { name: "T&E Tool",                    qty: 1, weight: "",       notes: "Machine Gunner Tool-Proficiency, MG-Einrichtung" },
    demo_tools:     { name: "Demolitions Tools",           qty: 1, weight: "",       notes: "Demolitionist Tool-Proficiency" },
    handler_tools:  { name: "Handler's Tools",             qty: 1, weight: "",       notes: "Dog Handler Tool-Proficiency" },
    b1ard:          { name: "B1ARD Kit",                   qty: 1, weight: "3.6 kg",  notes: "Tech Specialist Drohnen-Tool-Proficiency, B-1 Recon Drone + Controller" },
    drone_repair:   { name: "Drone Repair Kit",            qty: 1, weight: "",       notes: "Tech Specialist: DC 15 Int-Check zum Reparieren/Upgraden" },
    decon_kit:      { name: "Decontamination Kit",         qty: 1, weight: "",       notes: "Combat Medic Tool-Proficiency" },
    terrain_map:    { name: "Terrain Map Tools",           qty: 1, weight: "",       notes: "Unit Leader Tool-Proficiency" },

    // Packs
    pk_alice:       { name: "Main Rucksack (ALICE)",       qty: 1, weight: "3.0 kg",  notes: "High-capacity ~70 L" },
    pk_assault3:    { name: "3-Day Assault Pack",          qty: 1, weight: "1.5 kg",  notes: "Medium overnight, ~35 L" },
    pk_mr3dap:      { name: "Mystery Ranch 3DAP",          qty: 1, weight: "1.6 kg",  notes: "Premium assault pack, MOLLE" },
    pk_halftrack:   { name: "Eberlestock Halftrack",       qty: 1, weight: "3.2 kg",  notes: "Sniper pack mit Rifle-Scabbard" },
    pk_kifaru:      { name: "Kifaru EMR",                  qty: 1, weight: "3.5 kg",  notes: "Extended-mission ruck, ~85 L, high-capacity" },
    pk_civdaypack:  { name: "Civilian Daypack",            qty: 1, weight: "0.6 kg",  notes: "Low-profile book-bag, covert" },
    pk_duffel:      { name: "Duffel Bag",                  qty: 1, weight: "1.0 kg",  notes: "Soft-sided overflow, high-capacity" },
    pk_bugout:      { name: "Bug-Out Bag (civilian)",      qty: 1, weight: "1.0 kg",  notes: "Low-profile pre-packed grab bag, covert" },
    pk_pelican:     { name: "Pelican 1510 Case",           qty: 1, weight: "2.5 kg",  notes: "Rolling hard-shell, waterproof" },
    pk_chestrig:    { name: "Chest Rig (generic)",         qty: 1, weight: "0.8 kg",  notes: "Mags + Admin ohne Platten" },
    pk_crye_cpc:    { name: "Crye CPC",                    qty: 1, weight: "0.7 kg",  notes: "Minimalist combat pack-compatible chest rig" },
    pk_lbt1961g:    { name: "LBT-1961G",                   qty: 1, weight: "0.9 kg",  notes: "Classic SOF chest rig" },
    pk_mayflower:   { name: "Mayflower APC",               qty: 1, weight: "0.8 kg",  notes: "Low-profile assault panel" },
    pk_battlebelt:  { name: "Battle Belt",                 qty: 1, weight: "0.6 kg",  notes: "Padded war belt, Holster + Pouches" },
    pk_dump:        { name: "Dump Pouch",                  qty: 1, weight: "0.15 kg", notes: "Collapsible catchall for empty mags" },
    pk_admin:       { name: "Admin Pouch",                 qty: 1, weight: "0.2 kg",  notes: "Pens, Map, Notebook" },
    pk_riflemag:    { name: "Rifle Mag Pouch (x3)",        qty: 1, weight: "0.25 kg", notes: "3 Rifle-Magazine" },
    pk_pistolmag:   { name: "Pistol Mag Pouch (x2)",       qty: 1, weight: "0.1 kg",  notes: "2 Pistol-Magazine" },
    pk_ifakpouch:   { name: "Medical IFAK Pouch",          qty: 1, weight: "0.3 kg",  notes: "IFAK-Mount" },
    pk_hydration3:  { name: "Hydration Bladder 3L",        qty: 1, weight: "0.6 kg",  notes: "3 L Wasser + Drink-Tube" },
    pk_fannypack:   { name: "Concealment Fanny Pack",      qty: 1, weight: "0.3 kg",  notes: "Zivil EDC, covert, versteckt Pistole" },
    pk_messenger:   { name: "Messenger Bag",               qty: 1, weight: "0.5 kg",  notes: "Urban blend-in, covert" },
    pk_moneybelt:   { name: "Money Belt (concealment)",    qty: 1, weight: "0.2 kg",  notes: "Hidden zipper, Cash + Karten, covert" },
    pk_cashroll:    { name: "Cash Roll (small bills)",     qty: 1, weight: "0.3 kg",  notes: "~200 bills, covert" },
    pk_goldcoins:   { name: "Gold Coins (5x 1 oz)",        qty: 1, weight: "0.15 kg", notes: "Bullion, universal barter, covert" },
    pk_silvercoins: { name: "Silver Coins (roll, 20)",     qty: 1, weight: "0.3 kg",  notes: "1 oz silver rounds, covert" },
    pk_simcards:    { name: "Pre-paid SIM Cards (5)",      qty: 1, weight: "0.02 kg", notes: "Anonyme Mobilnummern, covert" },

    // Field Kit
    fk_canteen:     { name: "Canteen 1L",                  qty: 1, weight: "1.0 kg",  notes: "Steel/Plastik, voll" },
    fk_msr_filter:  { name: "MSR Water Filter",            qty: 1, weight: "0.3 kg",  notes: "Reinigt Field-Wasser" },
    fk_leatherman:  { name: "Leatherman Wave Multi-Tool",  qty: 1, weight: "0.25 kg", notes: "Zangen, Driver, Klinge, repair" },
    fk_mp600:       { name: "Gerber MP600 Multi-Tool",     qty: 1, weight: "0.3 kg",  notes: "Milspec Multi-Tool, repair" },
    fk_surefire:    { name: "Surefire M600DF",             qty: 1, weight: "0.2 kg",  notes: "1500 lm Waffenlicht, weiß" },
    fk_tactikka:    { name: "Petzl Tactikka Headlamp",     qty: 1, weight: "0.1 kg",  notes: "Weiß + Rot LED" },
    fk_fenix_e35r:  { name: "Fenix E35R Pocket Light",     qty: 1, weight: "0.1 kg",  notes: "EDC Taschenlampe" },
    fk_silva:       { name: "Silva Ranger Compass",        qty: 1, weight: "0.1 kg",  notes: "Baseplate Kompass" },
    fk_foretrex:    { name: "Garmin Foretrex 701 GPS",     qty: 1, weight: "0.15 kg", notes: "Armbanduhr GPS" },
    fk_survkit:     { name: "Survival Kit",                qty: 1, weight: "0.3 kg",  notes: "Feuerstein, Angel, Pfeife, Spiegel, Drahtsäge" },
    fk_etool:       { name: "Entrenching Tool (E-tool)",   qty: 1, weight: "1.0 kg",  notes: "Faltspaten, auch Waffe, breaching" },
    fk_crank_light: { name: "Hand-Crank Flashlight/Radio", qty: 1, weight: "0.4 kg",  notes: "Dynamo, keine Batterien" },
    fk_solarpanel:  { name: "Foldable Solar Panel (20 W)", qty: 1, weight: "0.6 kg",  notes: "USB-Output" },
    fk_powerbank:   { name: "Rugged Power Bank (20k mAh)", qty: 1, weight: "0.5 kg",  notes: "IP67, ~5 Phone-Charges" },
    fk_crank_usb:   { name: "Hand-Crank USB Generator",    qty: 1, weight: "0.6 kg",  notes: "Pocket Dynamo" },
    fk_handwarmers: { name: "Chemical Hand Warmers (10)",  qty: 1, weight: "0.1 kg",  notes: "Luftaktiviert, 8 h Wärme" },
    fk_tealights:   { name: "Tea Lights (pack of 20)",     qty: 1, weight: "0.1 kg",  notes: "Kleine Kerzen" },
    fk_lantern:     { name: "LED Camp Lantern",            qty: 1, weight: "0.4 kg",  notes: "~40 h auf AA" },
    fk_windup:      { name: "Mechanical Wind-Up Watch",    qty: 1, weight: "0.1 kg",  notes: "Self-winding, keine Batterie" },
    fk_roadatlas:   { name: "Road Atlas (regional)",       qty: 1, weight: "0.8 kg",  notes: "Zivil Fahratlas" },
    fk_falkplan:    { name: "Street Atlas (Falk-Plan)",    qty: 1, weight: "0.3 kg",  notes: "Deutscher Stadtplan, ÖPNV" },
    fk_topo:        { name: "Topographic Map 1:25k",       qty: 1, weight: "0.1 kg",  notes: "Milgrade Geländekarte" },
    fk_laminated:   { name: "Waterproof Laminated Map",    qty: 1, weight: "0.15 kg", notes: "Wetterfest, Markierungen abwischbar" },
    fk_mapcase:     { name: "Map Case (waterproof)",       qty: 1, weight: "0.15 kg", notes: "Klar-Pouch für Karten" },
    fk_chinagraph:  { name: "Chinagraph / Grease Pencil",  qty: 1, weight: "0.02 kg", notes: "Markiert auf Laminat und Acetate" },
    fk_protractor:  { name: "Map Protractor (MGRS/UTM)",   qty: 1, weight: "0.05 kg", notes: "Gitterkoordinaten 1:25k/1:50k" },
    fk_rangerbeads: { name: "Ranger Beads / Pace Counter", qty: 1, weight: "0.02 kg", notes: "13-Bead Paracord, Distanzzähler" },
    fk_lensatic:    { name: "Lensatic Compass (M-1950)",   qty: 1, weight: "0.1 kg",  notes: "Milspec Sighting Compass, Tritium" },
    fk_sextant:     { name: "Sextant + Nautical Almanac",  qty: 1, weight: "1.5 kg",  notes: "Celestial Nav, keine Infrastruktur" },

    // Comms
    uhf_radio:      { name: "UHF Radio",                   qty: 1, weight: "",       notes: "Standard Military Funk" },
    sat_radio:      { name: "Satellite Radio",             qty: 1, weight: "",       notes: "Long-Range via Satellit" },
    crypto_key:     { name: "Crypto Key",                  qty: 1, weight: "",       notes: "Radio Ops Training L2, verschlüsselter Funk" },
    cm_walkie_frs:  { name: "Walkie-talkie (FRS)",         qty: 1, weight: "0.2 kg",  notes: "Zivil UHF, unverschlüsselt, short-range" },
    cm_dtr600:      { name: "Motorola DTR600",             qty: 1, weight: "0.3 kg",  notes: "Digital trunked, encrypted, short-range" },
    cm_apx8000:     { name: "Motorola APX 8000",           qty: 1, weight: "0.5 kg",  notes: "Multi-band Squad-Radio, encrypted" },
    cm_prc148:      { name: "Harris AN/PRC-148 JEM",       qty: 1, weight: "0.9 kg",  notes: "Standard SOF Handheld, crypto-fähig" },
    cm_prc152a:     { name: "Harris AN/PRC-152A",          qty: 1, weight: "1.0 kg",  notes: "MBITR, JTRS compliant, encrypted" },
    cm_prc117g:     { name: "AN/PRC-117G",                 qty: 1, weight: "4.5 kg",  notes: "Manpack Sat + HF/UHF/VHF, encrypted, long-range" },
    cm_iridium:     { name: "Iridium 9575 Sat Phone",      qty: 1, weight: "0.3 kg",  notes: "Global Sat Voice/Data, long-range" },
    cm_thuraya:     { name: "Thuraya XT-PRO",              qty: 1, weight: "0.3 kg",  notes: "Sat Phone, regional, long-range" },
    cm_ta312:       { name: "Field Phone (TA-312)",        qty: 1, weight: "4.5 kg",  notes: "Drahtiges Feldtelefon, short-range" },
    cm_ft818:       { name: "Yaesu FT-818 (HF portable)",  qty: 1, weight: "0.9 kg",  notes: "6-band HF/VHF/UHF QRP, long-range" },
    cm_baofeng:     { name: "Baofeng UV-5R",               qty: 1, weight: "0.2 kg",  notes: "Dual-band Amateur VHF/UHF, billig" },
    cm_gotenna:     { name: "goTenna Pro X (mesh node)",   qty: 1, weight: "0.1 kg",  notes: "Bluetooth Mesh, off-grid Text + GPS, encrypted" },
    cm_meshtastic:  { name: "Meshtastic LoRa Node",        qty: 1, weight: "0.05 kg", notes: "LoRa Mesh, DIY, encrypted" },
    cm_thd74:       { name: "Kenwood TH-D74 (APRS)",       qty: 1, weight: "0.4 kg",  notes: "Amateur Packet, Position Reports" },
    cm_prc112:      { name: "PRC-112 Survival Radio",      qty: 1, weight: "0.7 kg",  notes: "Aviator Survival Beacon + Voice, long-range" },
    cm_comtac:      { name: "Peltor ComTac III",           qty: 1, weight: "0.4 kg",  notes: "Electronic Ear-Pro mit PTT-Integration" },
    cm_invisio:     { name: "Invisio X5 Earpiece",         qty: 1, weight: "0.1 kg",  notes: "In-Ear covert Comm" },
    cm_throatmic:   { name: "Throat Mic",                  qty: 1, weight: "0.1 kg",  notes: "Kehlkopf-Mikro, PTT-kompatibel" },
    cm_bone:        { name: "Bone-Conduction Headset",     qty: 1, weight: "0.1 kg",  notes: "Lässt Ohren frei" },
    cm_curlycoil:   { name: "Earpiece (curly coil)",       qty: 1, weight: "0.05 kg", notes: "Protective-Detail Earpiece, covert" },
    cm_kyk13:       { name: "Crypto Key (KYK-13)",         qty: 1, weight: "0.3 kg",  notes: "Lädt Schlüssel in kompatible Radios" },
    cm_longwhip:    { name: "Long-Whip Antenna (10 ft)",   qty: 1, weight: "0.3 kg",  notes: "Erweitert Radio-Reichweite, long-range" },
    cm_vs17:        { name: "VS-17 Signal Panel",          qty: 1, weight: "0.3 kg",  notes: "Orange/Pink Marker, Ground-to-Air ID" },

    // Optics
    op_pvs7:        { name: "PVS-7 Goggle",                qty: 1, weight: "0.7 kg",  notes: "Gen 3 Binocular NVG, Budget" },
    op_pvs14:       { name: "PVS-14 Monocular",            qty: 1, weight: "0.4 kg",  notes: "Helmmontiert oder handgehalten, SOF Standard" },
    op_pvs31:       { name: "PVS-31 Binocular",            qty: 1, weight: "0.5 kg",  notes: "White-Phosphor Dual-Tube, Tiefenwahrnehmung" },
    op_gpnvg18:     { name: "GPNVG-18 Panoramic",          qty: 1, weight: "0.8 kg",  notes: "Four-Tube Panorama, Tier-1 Issue" },
    op_gen2:        { name: "Civilian Gen 2 Monocular",    qty: 1, weight: "0.5 kg",  notes: "Niedrigere Auflösung, nicht milspec" },
    op_flir_tk:     { name: "FLIR Scout TK",               qty: 1, weight: "0.2 kg",  notes: "Pocket Thermal Monocular, short-range" },
    op_breach:      { name: "FLIR Breach PTQ136",          qty: 1, weight: "0.2 kg",  notes: "Helm-Montage Thermal Monocular" },
    op_reapir:      { name: "Trijicon REAP-IR",            qty: 1, weight: "1.0 kg",  notes: "Rifle-Mount Thermal Scope, magnified" },
    op_snipeir:     { name: "Trijicon SNIPE-IR Clip-On",   qty: 1, weight: "0.8 kg",  notes: "Montiert vor Tag-Optik" },
    op_steiner:     { name: "Steiner M830r Binoculars",    qty: 1, weight: "0.8 kg",  notes: "8x30 Milspec" },
    op_mk4:         { name: "Leupold Mk4 Spotter",         qty: 1, weight: "2.0 kg",  notes: "12-40x60 Tactical Spotter" },
    op_vortex:      { name: "Vortex Solo Monocular",       qty: 1, weight: "0.3 kg",  notes: "10x36 Pocket Monocular" },
    op_geovid:      { name: "Leica Geovid Rangefinder",    qty: 1, weight: "1.0 kg",  notes: "10x42 Laser-RF Binocular, long-range" },
    op_plrf25c:     { name: "Vectronix PLRF25C Rangefinder", qty: 1, weight: "0.6 kg", notes: "Handheld Laser-RF, ~6 km" },

    // Electronics
    el_rf_jammer:   { name: "Portable RF Jammer",          qty: 1, weight: "1.5 kg",  notes: "Backpack, ~200 m Funkstörung" },
    el_cdrone_jam:  { name: "Counter-Drone Jammer",        qty: 1, weight: "2.5 kg",  notes: "Rifle-shaped, stört Drohnen-Link" },
    el_scanner:     { name: "Uniden BCD436HP Scanner",     qty: 1, weight: "0.3 kg",  notes: "Zivil-Scanner, detects-rf" },
    el_rfdetect:    { name: "RF Emission Detector",        qty: 1, weight: "0.2 kg",  notes: "Bug-Sweep, detects-rf" },
    el_toughbook:   { name: "Panasonic Toughbook",         qty: 1, weight: "3.5 kg",  notes: "Feldrechner, Hacking, Drohnen, Analyse" },
    el_faraday_ph:  { name: "Faraday Pouch (phone)",       qty: 1, weight: "0.1 kg",  notes: "RF-Blocking für Handy" },
    el_faraday_lt:  { name: "Faraday Bag (laptop)",        qty: 1, weight: "0.4 kg",  notes: "RF-Blocking für Laptop/Radios" },
    el_faraday_can: { name: "Faraday Ammo Can (lined)",    qty: 1, weight: "2.5 kg",  notes: "Abgeschirmte Stahlbox" },
    el_rtlsdr:      { name: "RTL-SDR Dongle",              qty: 1, weight: "0.05 kg", notes: "USB SDR, Wideband, detects-rf" },
    el_audiobug:    { name: "Audio Bug (1 cm)",            qty: 1, weight: "0.01 kg", notes: "Lauscht in 20 ft, 8 h Batterie, covert" },
    el_pir:         { name: "Motion Sensor (PIR)",         qty: 1, weight: "0.02 kg", notes: "Pingt alle 6 s auf Bewegung in 20 ft, 24 h" },
    el_microcam:    { name: "Micro Camera + Transmitter",  qty: 1, weight: "0.05 kg", notes: "Pinhole Cam, Stream, covert" },
    el_parabolic:   { name: "Parabolic Microphone",        qty: 1, weight: "1.0 kg",  notes: "Direktionale Langstrecken-Audio" },
    el_gps_covert:  { name: "GPS Tracker (covert)",        qty: 1, weight: "0.05 kg", notes: "Magnetisch, Sat-Uplink alle 5 min, long-range" },
    el_lockpicks:   { name: "Lock-Pick Set",               qty: 1, weight: "0.2 kg",  notes: "Tension-Wrench + Picks für Pin-Tumbler" },
    el_bumpkey:     { name: "Bump-Key Set",                qty: 1, weight: "0.1 kg",  notes: "Quick-and-dirty Pin-Tumbler Bypass" },
    el_boltcutters: { name: "Bolt Cutters (18\")",         qty: 1, weight: "1.5 kg",  notes: "Schneidet Schlösser, Ketten, leichten Rebar" },
    el_hydraulic:   { name: "Hydraulic Spreader",          qty: 1, weight: "4.0 kg",  notes: "Jaws-of-Life, forciert Türen" },
    el_thermite_pen:{ name: "Thermite Pen (torch)",        qty: 1, weight: "0.3 kg",  notes: "Kurz brennender Schneidbrenner" },
    el_soflam:      { name: "Laser Designator (SOFLAM)",   qty: 1, weight: "5.5 kg",  notes: "Malt Ziele für Laser-Munition, 10 km, long-range" },
    el_ir_strobe:   { name: "IR Strobe (Phoenix beacon)",  qty: 1, weight: "0.05 kg", notes: "Identifiziert Friendlies für NVG/Thermal" },
    el_chemlight:   { name: "Chemical Light (chemlight)",  qty: 1, weight: "0.02 kg", notes: "Einmal-Knicklicht, IR-Varianten" },
    el_buttset:     { name: "Lineman's Butt Set",          qty: 1, weight: "0.8 kg",  notes: "Tapping analoger Telefonleitungen" },
    el_yubikey:     { name: "YubiKey 5",                   qty: 1, weight: "0.01 kg", notes: "USB/NFC 2FA Key" },
    el_ledger:      { name: "Ledger Nano Hardware Wallet", qty: 1, weight: "0.02 kg", notes: "Cold Storage für Krypto-Keys, covert" },
    el_trezor:      { name: "Trezor Model T",              qty: 1, weight: "0.02 kg", notes: "Touchscreen Cold Storage Wallet, covert" },
    el_ironkey:     { name: "IronKey Encrypted USB 32GB",  qty: 1, weight: "0.03 kg", notes: "Hardware-verschlüsselter Flash, Auto-Wipe, covert" },
    el_inverter:    { name: "Portable Inverter Generator", qty: 1, weight: "12 kg",   notes: "1 kW leiser Benzingenerator" },
    el_12v_usb:     { name: "12V-to-USB Adapter",          qty: 1, weight: "0.05 kg", notes: "Zigaretten-Stecker USB-Lader" },
    el_ups:         { name: "UPS Battery Pack (600 VA)",   qty: 1, weight: "5 kg",    notes: "Unterbrechungsfreie Versorgung" },

    // Drones
    dr_black_hornet:{ name: "Black Hornet Nano",           qty: 1, weight: "0.1 kg",  notes: "Palm-sized Recon, leise, 25 min, covert + NV" },
    dr_mavic3:      { name: "DJI Mavic 3 (civilian)",      qty: 1, weight: "0.9 kg",  notes: "COTS Quadcopter, 45 min, magnified" },
    dr_switchblade: { name: "Switchblade 300",             qty: 1, weight: "2.5 kg",  notes: "Einmal-Loitering-Munition, 10 km, breaching" },
    dr_puma:        { name: "Puma AE (fixed-wing)",        qty: 1, weight: "6.3 kg",  notes: "Hand-launched, 2 h, 20 km, long-range + NV" },
    dr_raven:       { name: "Raven RQ-11B",                qty: 1, weight: "1.9 kg",  notes: "Man-portable Fixed-Wing, 90 min, long-range" },

    // Demolitions
    dm_c4_025:      { name: "C4 Block (0.25 lb)",          qty: 1, weight: "0.11 kg", notes: "Kleinster nützlicher Block, teilbar, breaching" },
    dm_c4_05:       { name: "C4 Block (0.5 kg)",           qty: 1, weight: "0.5 kg",  notes: "Standard Demo Block, breaching" },
    dm_c4_1:        { name: "C4 Block (1 kg)",             qty: 1, weight: "1.0 kg",  notes: "Größere Strukturladung, breaching" },
    dm_detcord:     { name: "Detonation Cord (per ft)",    qty: 1, weight: "0.05 kg", notes: "Flexible HE-Schnur, nach Länge, breaching" },
    dm_thermite:    { name: "Thermite Grenade",            qty: 1, weight: "0.8 kg",  notes: "Brennt durch Stahl, breaching" },
    dm_flex_shaped: { name: "Flex Linear Shaped Charge",   qty: 1, weight: "0.4 kg",  notes: "Flexible Schneidladung, breaching" },
    dm_bowtie:      { name: "Bow Tie Charge",              qty: 1, weight: "0.2 kg",  notes: "Kleine Det-Cord-Ladung, Lock-Defeat, breaching" },
    dm_xcharge:     { name: "X Charge",                    qty: 1, weight: "0.3 kg",  notes: "Tür-Breach Det-Cord X, breaching" },
    dm_strip:       { name: "Strip Charge (sticky)",       qty: 1, weight: "0.5 kg",  notes: "Klebende lineare Breaching-Strip, breaching" },
    dm_water:       { name: "Water-Impulse Charge",        qty: 1, weight: "2.0 kg",  notes: "Low-Overpressure Breach, breaching" },
    dm_cap_elec:    { name: "Blasting Cap (electric)",     qty: 1, weight: "0.02 kg", notes: "Initiator, gezündet über Draht + Clacker" },
    dm_cap_nonelec: { name: "Blasting Cap (non-electric)", qty: 1, weight: "0.02 kg", notes: "Gezündet über Shock-Tube oder Zeitzünder" },
    dm_m81:         { name: "M81 Clacker",                 qty: 1, weight: "0.4 kg",  notes: "Handheld Pulsgeber für elektrische Caps" },
    dm_m57:         { name: "M57 Firing Device",           qty: 1, weight: "0.5 kg",  notes: "Claymore-Pulsgeber" },
    dm_firewire:    { name: "500 ft Firing Wire Spool",    qty: 1, weight: "1.5 kg",  notes: "Twin-Lead Demo-Draht, Stand-off" },
    dm_remote_det:  { name: "Remote Detonator (RF)",       qty: 1, weight: "0.3 kg",  notes: "Funk-getriggert, ~1 km" },
    dm_remote_caps: { name: "Remote Blasting Caps",        qty: 1, weight: "0.05 kg", notes: "Gepaart mit Remote Detonator" },
    dm_timefuse:    { name: "Time Fuse (per ft)",          qty: 1, weight: "0.02 kg", notes: "Brennt ~40 s/ft" },
    dm_shocktube:   { name: "Shock Tube (per ft)",         qty: 1, weight: "0.02 kg", notes: "Non-elektrische Initiationslinie" },

    // Medical
    morphine:       { name: "Morphine",                    qty: 1, weight: "0.02 kg", notes: "Heal 6d6 HP jede Triage-Stufe; Con-Save DC=HP oder bewusstlos. 3+ Uses/24h Sucht" },
    quickclot:      { name: "Quick Clot",                  qty: 1, weight: "0.05 kg", notes: "Stoppt Bleed/Major Bleed. Con-Save DC 15 oder bewusstlos" },
    narcotics:      { name: "Narcotics",                   qty: 1, weight: "0.02 kg", notes: "1d6 HP + 1d6 für 3 weitere Runden. 4+ Uses/24h = Suchtrisiko" },
    iv_500:         { name: "I.V. 500cc",                  qty: 1, weight: "0.6 kg",  notes: "1 Min Setup, 5 Min Admin. Regain 1 HP alle 2 Rd. Nur Green/Yellow/Orange" },
    liquid_skin:    { name: "Liquid Skin Patch",           qty: 1, weight: "0.02 kg", notes: "Heal 2d6 HP. Nur Orange/Red Triage" },
    epi:            { name: "Epinephrine",                 qty: 1, weight: "0.02 kg", notes: "Auf 0-HP-Ziel in 3 Rd: regain 6d4 HP. 1x/Tag sicher, sonst Con-Save" },
    combat_pills:   { name: "Combat Pill Pack",            qty: 1, weight: "0.02 kg", notes: "Nach 24h: Adv. auf Disease/Poison-Checks für 48h" },
    diazepam:       { name: "5 Days Diazepam",             qty: 1, weight: "0.05 kg", notes: "Nach 5 Tagen Einnahme: 1 Stufe Shaken weniger" },
    md_ifak:        { name: "IFAK (individual)",           qty: 1, weight: "0.8 kg",  notes: "10 Uses + 2 Tourniquets, stops-bleed" },
    md_ifak_conc:   { name: "Concealable IFAK",            qty: 1, weight: "0.4 kg",  notes: "Schlankes Zivil-Med-Pouch, covert" },
    md_trauma_bag:  { name: "Trauma Bag",                  qty: 1, weight: "3.5 kg",  notes: "Combat-Medic Issue; IFAK + Trauma Kit + Med-Grade-Slot" },
    md_trauma_kit:  { name: "Trauma Kit",                  qty: 1, weight: "1.5 kg",  notes: "5 Uses, Surgical-Grade Wundversorgung" },
    md_corpsman:    { name: "Corpsman's Bag",              qty: 1, weight: "5.0 kg",  notes: "15th-Level Combat Medic Issue, BAS-Zugang" },
    md_k9_ifak:     { name: "K-9 IFAK",                    qty: 1, weight: "0.6 kg",  notes: "Hund-Trauma-Kit, Maulkorb, canine TQ, Pfotentape" },
    md_stethoscope: { name: "Stethoscope",                 qty: 1, weight: "0.15 kg", notes: "Lunge/Herz, Brustwunden-Assessment" },
    md_pulseox:     { name: "Pulse Oximeter",              qty: 1, weight: "0.05 kg", notes: "SpO2 + HF, Hypoxie" },
    md_bp_cuff:     { name: "Blood-Pressure Cuff",         qty: 1, weight: "0.3 kg",  notes: "Sphygmomanometer, Schock-Erkennung" },
    md_thermom:     { name: "Digital Thermometer",         qty: 1, weight: "0.05 kg", notes: "Kerntemp., Infektion, Hypothermie" },
    md_glucometer:  { name: "Glucometer + Strips",         qty: 1, weight: "0.1 kg",  notes: "Blutzucker" },
    md_otoscope:    { name: "Otoscope + Ophthalmoscope",   qty: 1, weight: "0.2 kg",  notes: "Ohren/Augen, TBI Pupillen" },
    md_ultrasound:  { name: "Butterfly iQ Ultrasound",     qty: 1, weight: "0.3 kg",  notes: "Phone-tethered FAST-Exam" },
    md_ekg:         { name: "Handheld EKG (AliveCor)",     qty: 1, weight: "0.1 kg",  notes: "Single-Lead EKG, Arrhythmie" },
    md_penlight:    { name: "Penlight",                    qty: 1, weight: "0.05 kg", notes: "Pupillen, Rachen" },
    md_cric:        { name: "Cricothyrotomy Kit",          qty: 1, weight: "0.1 kg",  notes: "Surgical Airway, last-resort, revives" },
    md_king_lt:     { name: "King LT Airway",              qty: 1, weight: "0.1 kg",  notes: "Blind-Insertion Airway, revives" },
    md_et_tube:     { name: "ET Tube Kit",                 qty: 1, weight: "0.4 kg",  notes: "Laryngoskop + Tuben, revives" },
    md_bvm:         { name: "Bag-Valve Mask (BVM)",        qty: 1, weight: "0.4 kg",  notes: "Manuelle Beatmung, CPR, revives" },
    md_opa:         { name: "OPA Set",                     qty: 1, weight: "0.05 kg", notes: "Oropharyngeal Adjuncts, revives" },
    md_suture:      { name: "Suture Kit",                  qty: 1, weight: "0.1 kg",  notes: "Nadelhalter, Pinzette, Faden, Schere" },
    md_stapler:     { name: "Surgical Stapler",            qty: 1, weight: "0.15 kg", notes: "Schneller Hautverschluss" },
    md_scalpel:     { name: "Scalpel Set",                 qty: 1, weight: "0.1 kg",  notes: "#10/#11/#15 Klingen + Griff" },
    md_hemostats:   { name: "Hemostats / Forceps",         qty: 1, weight: "0.1 kg",  notes: "Blut-Clamping, Fremdkörperentfernung" },
    md_suction:     { name: "Portable Suction (manual)",   qty: 1, weight: "0.5 kg",  notes: "V-Vac, Atemweg von Blut/Erbrochenem" },
    md_bonesaw:     { name: "Bone Saw (field amp.)",       qty: 1, weight: "0.6 kg",  notes: "Last-resort traumatische Amputation" },
    md_softw:       { name: "SOF-T Wide Tourniquet",       qty: 1, weight: "0.1 kg",  notes: "Windlass TQ, stops-bleed" },
    md_cat:         { name: "CAT (Gen 7) Tourniquet",      qty: 1, weight: "0.1 kg",  notes: "NATO-Standard Windlass TQ, stops-bleed" },
    md_jtq:         { name: "Junctional TQ (SAM)",         qty: 1, weight: "0.5 kg",  notes: "Leiste/Achsel, stops-bleed" },
    md_israeli:     { name: "Israeli Emergency Bandage",   qty: 1, weight: "0.08 kg", notes: "Druckverband mit integriertem Druckbalken, stops-bleed" },
    md_qc_gauze:    { name: "QuickClot Combat Gauze",      qty: 1, weight: "0.05 kg", notes: "Hämostatisches Kaolin-Gaze, stops-bleed" },
    md_celox:       { name: "Celox Hemostatic Granules",   qty: 1, weight: "0.05 kg", notes: "Pour-in Hämostat für tiefe Punktwunden" },
    md_chestseal:   { name: "Chest Seal (vented)",         qty: 1, weight: "0.05 kg", notes: "Okklusivpflaster für saugende Thoraxwunde" },
    md_decomp:      { name: "Decompression Needle (14g)",  qty: 1, weight: "0.05 kg", notes: "Tension-Pneumothorax, revives" },
    md_ketamine:    { name: "Ketamine Auto-Injector",      qty: 1, weight: "0.02 kg", notes: "Pain + Dissoziation, TCCC-Standard, revives" },
    md_fentanyl:    { name: "Fentanyl Lozenge (OTFC)",     qty: 1, weight: "0.01 kg", notes: "Buccal Opioid, keine IV nötig, revives" },
    md_narcan:      { name: "Narcan (Naloxone) Spray",     qty: 1, weight: "0.05 kg", notes: "Opioid-Overdose Umkehr, revives" },
    md_txa:         { name: "Tranexamic Acid (TXA)",       qty: 1, weight: "0.02 kg", notes: "IV/IM Anti-Fibrinolytikum, früh geben, stops-bleed" },
    md_zofran:      { name: "Ondansetron (Zofran) ODT",    qty: 1, weight: "0.01 kg", notes: "Anti-Übelkeit Dissolve-Tab" },
    md_ringers:     { name: "Ringer's Lactate IV (1 L)",   qty: 1, weight: "1.1 kg",  notes: "Bevorzugte Trauma-Resuscitation, revives" },
    md_dexedrine:   { name: "Dexedrine Go-Pill",           qty: 1, weight: "0.01 kg", notes: "Amphetamin, ignoriert 1. Exhaustion-Stufe 4 h, Rebound danach" },
    md_modafinil:   { name: "Modafinil",                   qty: 1, weight: "0.01 kg", notes: "Wachheit, ~12 h Schlaf-Resistenz" },
    md_ambien:      { name: "Ambien No-Go-Pill",           qty: 1, weight: "0.01 kg", notes: "Schneller Schlaf, Crew-Rest nach Ops" },
    md_doxy:        { name: "Doxycycline",                 qty: 1, weight: "0.02 kg", notes: "Breitspektrum-AB + Malaria-Prophylaxe" },
    md_cipro:       { name: "Ciprofloxacin (Cipro)",       qty: 1, weight: "0.02 kg", notes: "Breitspektrum-AB, GI + Respir." },
    md_azithro:     { name: "Azithromycin (Z-pack)",       qty: 1, weight: "0.02 kg", notes: "5-Tage AB, Respir./STD" },
    md_imodium:     { name: "Loperamide (Imodium)",        qty: 1, weight: "0.01 kg", notes: "Anti-Diarrhoe" },
    md_ors:         { name: "Oral Rehydration Salts",      qty: 1, weight: "0.05 kg", notes: "Dehydration (Hitze, GI, Blutverlust)" },
    md_benadryl:    { name: "Diphenhydramine (Benadryl)",  qty: 1, weight: "0.02 kg", notes: "Antihistaminikum, milde Sedierung" },
    md_duodote:     { name: "DuoDote Auto-Injector",       qty: 1, weight: "0.05 kg", notes: "Atropin + Pralidoxim, Nervenkampfstoff, revives" },
    md_mark1:       { name: "Mark I NAAK",                 qty: 1, weight: "0.05 kg", notes: "Legacy Nervenagent-Antidot, revives" },
    md_cana:        { name: "CANA (Diazepam AI)",          qty: 1, weight: "0.05 kg", notes: "Anti-Seizure, Nervenagent-Exposition, revives" },
    md_atropine:    { name: "Atropine (syringe)",          qty: 1, weight: "0.02 kg", notes: "Bradykardie, Organophosphat, revives" },
    md_pam:         { name: "Pralidoxime (2-PAM)",         qty: 1, weight: "0.02 kg", notes: "Nervenagent-Antidot, mit Atropin, revives" },
    md_cyanokit:    { name: "Cyanokit",                    qty: 1, weight: "1.2 kg",  notes: "IV Cyanid-Antidot, Rauch-Inhalation, revives" },
    md_m8:          { name: "M8 Chemical Paper",           qty: 1, weight: "0.02 kg", notes: "Farbwechsel, erkennt flüssige Nerven/Blistern" },
    md_m9:          { name: "M9 Chemical Tape",            qty: 1, weight: "0.05 kg", notes: "Adhäsive M8-Version" },
    md_m256a1:      { name: "M256A1 Detection Kit",        qty: 1, weight: "0.3 kg",  notes: "Manual Test Card, Agent-Klasse" },
    md_rsdl:        { name: "RSDL Decon Lotion",           qty: 1, weight: "0.05 kg", notes: "Reactive Skin Decon, entfernt Flüssigagenten" },
    md_ki:          { name: "Potassium Iodide (KI)",       qty: 1, weight: "0.02 kg", notes: "Schilddrüsenschutz nach Radiologischer Exposition" },
    md_tccc_card:   { name: "TCCC Casualty Card (DD 1380)",qty: 1, weight: "0.01 kg", notes: "Write-in-the-Rain, Verletzungen/Zeiten" },
    md_sharpie:     { name: "Permanent Marker (Sharpie)",  qty: 1, weight: "0.02 kg", notes: "TQ-Applikationszeit auf Stirn markieren" },
    md_triage_tags: { name: "Triage Tag Set (METTAG)",     qty: 1, weight: "0.05 kg", notes: "4-Farb Tear-Off Triage Tags" },
    md_med_notebook:{ name: "Field Medical Notebook",      qty: 1, weight: "0.1 kg",  notes: "Wasserfest, Schicht-Notizen, Vitals" },

    // Consumables
    cn_mre:         { name: "MRE (24h ration)",            qty: 1, weight: "1.1 kg",  notes: "1 Tag Kalorien; 3 Mahlzeiten + Heater + Snacks" },
    cn_mre_entree:  { name: "MRE Entrée only",             qty: 1, weight: "0.4 kg",  notes: "Hauptgang ausgeschnitten, weight-cut" },
    cn_mre_cake:    { name: "MRE Pound Cake",              qty: 1, weight: "0.1 kg",  notes: "Morale-Favorit, MRE-Trade-Währung" },
    cn_fsr:         { name: "First Strike Ration (FSR)",   qty: 1, weight: "0.9 kg",  notes: "SOF eat-on-the-move, kein Heater" },
    cn_lrp:         { name: "Long-Range Patrol (LRP)",     qty: 1, weight: "0.3 kg",  notes: "Gefriergetrocknet, Heißwasser nötig" },
    cn_hdr:         { name: "Humanitarian Daily Ration",   qty: 1, weight: "0.9 kg",  notes: "2000 kcal, vegetarisch" },
    cn_epa:         { name: "EPa (Einmannpackung)",        qty: 1, weight: "1.6 kg",  notes: "Bundeswehr 1-Tag-Ration, Typ I-IV" },
    cn_epa_leber:   { name: "EPa Leberwurst-Tube",         qty: 1, weight: "0.1 kg",  notes: "Leberwurst in Tube, EPa-Klassiker" },
    cn_epa_corned:  { name: "EPa Corned Beef",             qty: 1, weight: "0.2 kg",  notes: "Rindfleisch in Dose, EPa-Staple" },
    cn_epa_cheese:  { name: "EPa Schmelzkäse-Tube",        qty: 1, weight: "0.1 kg",  notes: "Schmelzkäse in Tube" },
    cn_clifbar:     { name: "Clif Bar",                    qty: 1, weight: "0.07 kg", notes: "Zivil Energieriegel, 250 kcal" },
    cn_snickers:    { name: "Snickers Bar",                qty: 1, weight: "0.05 kg", notes: "Trade-Währung, Morale" },
    cn_proteinbar:  { name: "Protein Bar",                 qty: 1, weight: "0.07 kg", notes: "Zivil/Gym Staple" },
    cn_ritter:      { name: "Ritter Sport (100 g)",        qty: 1, weight: "0.1 kg",  notes: "Deutsche Schokolade" },
    cn_haribo:      { name: "Haribo Goldbären",            qty: 1, weight: "0.2 kg",  notes: "Universal Trade-Währung" },
    cn_landjaeger:  { name: "Landjäger (pair)",            qty: 1, weight: "0.1 kg",  notes: "Hart geräucherte Wurst, Pocket-Carry" },
    cn_cabanossi:   { name: "Cabanossi (stick)",           qty: 1, weight: "0.1 kg",  notes: "Hart geräucherte Wurst, shelf-stable" },
    cn_knaecke:     { name: "Knäckebrot",                  qty: 1, weight: "0.25 kg", notes: "Deutsche Crispbread" },
    cn_jerky:       { name: "Beef Jerky (4 oz)",           qty: 1, weight: "0.1 kg",  notes: "Shelf-stable Protein" },
    cn_trailmix:    { name: "Trail Mix (4 oz)",            qty: 1, weight: "0.1 kg",  notes: "Fett + Kohlenhydrate" },
    cn_hardtack:    { name: "Hard Tack / Pilot Bread",     qty: 1, weight: "0.1 kg",  notes: "Survival-Keks, unbegrenzte Lagerzeit" },
    cn_mountain:    { name: "Mountain House Dehyd.",       qty: 1, weight: "0.15 kg", notes: "Gefriergetrocknet, 2 Tassen Heißwasser" },
    cn_3600:        { name: "3600 kcal Survival Bar",      qty: 1, weight: "0.6 kg",  notes: "Dichte Kalorien-Brikette, 5 Jahre" },
    cn_maggi_cubes: { name: "Maggi Bouillon Cubes",        qty: 1, weight: "0.05 kg", notes: "Würzt fades Feldessen" },
    cn_maggi_wuerz: { name: "Maggi Würze (Flasche)",       qty: 1, weight: "0.1 kg",  notes: "Flüssigwürze" },
    cn_water_1l:    { name: "Water (1 L)",                 qty: 1, weight: "1.0 kg",  notes: "Eine Feldflasche, Tagesbedarf 3-4 L" },
    cn_sprudel:     { name: "Sparkling Mineral Water 0.5L",qty: 1, weight: "0.5 kg",  notes: "Sprudel, Deutsches Default" },
    cn_apfelschorle:{ name: "Apfelschorle (0.5 L)",        qty: 1, weight: "0.5 kg",  notes: "Apfelsaft + Sprudel" },
    cn_mezzomix:    { name: "Mezzo Mix (can)",             qty: 1, weight: "0.35 kg", notes: "Cola + Orange, Deutsch" },
    cn_fritzkola:   { name: "Fritz-Kola (0.33 L)",         qty: 1, weight: "0.4 kg",  notes: "Craft Cola, viel Koffein" },
    cn_clubmate:    { name: "Club-Mate (0.5 L)",           qty: 1, weight: "0.55 kg", notes: "Koffeinierter Yerba-Mate" },
    cn_ripit:       { name: "Rip It Energy Drink",         qty: 1, weight: "0.4 kg",  notes: "SOF Staple, ~100 mg Koffein" },
    cn_gatorade:    { name: "Gatorade / Electrolyte",      qty: 1, weight: "0.05 kg", notes: "Single-Serve Pulver, Hitzekasualten" },
    cn_coffee:      { name: "Instant Coffee Packet",       qty: 1, weight: "0.01 kg", notes: "Morgenritual, MRE-issued" },
    cn_kroenung:    { name: "Jacobs Krönung Stick",        qty: 1, weight: "0.02 kg", notes: "Deutsche Instant-Coffee-Stick" },
    cn_starbucks:   { name: "Starbucks Via Packet",        qty: 1, weight: "0.01 kg", notes: "Premium Instant, Morale-Upgrade" },
    cn_tea:         { name: "Tea Bag",                     qty: 1, weight: "0.01 kg", notes: "Schwarz, Grün oder Kräuter" },
    cn_gum_caf:     { name: "Military Energy Gum (2 pcs)", qty: 1, weight: "0.01 kg", notes: "~100 mg Koffein/Stück, rapid" },
    cn_beer:        { name: "Beer (0.5 L)",                qty: 1, weight: "0.55 kg", notes: "Generisches Lager, Bundeswehr-Tradition" },
    cn_oettinger:   { name: "Oettinger (0.5 L)",           qty: 1, weight: "0.55 kg", notes: "Billigstes Bier Deutschlands" },
    cn_whiskey:     { name: "Hip Flask (Whiskey 8 oz)",    qty: 1, weight: "0.3 kg",  notes: "Morale, Bestechung" },
    cn_jaeger:      { name: "Jägermeister Miniatur",       qty: 1, weight: "0.08 kg", notes: "Kräuterlikör, 40 mL" },
    cn_korn:        { name: "Korn/Schnaps-Flasche 200 mL", qty: 1, weight: "0.3 kg",  notes: "Klarer Kornschnaps, Bestechungswährung" },
    cn_mini_liquor: { name: "Mini-Bottle (50 mL)",         qty: 1, weight: "0.06 kg", notes: "Flugzeug-Flasche, Bestechungswährung" },
    cn_aquatabs:    { name: "Water Purification Tablets",  qty: 1, weight: "0.05 kg", notes: "50 Tabs, ~50 L Feldwasser" },
    cn_cigs:        { name: "Cigarettes (pack of 20)",     qty: 1, weight: "0.03 kg", notes: "Trade-Währung weltweit" },
    cn_carton:      { name: "Cigarette Carton (10 pks)",   qty: 1, weight: "0.3 kg",  notes: "Bulk Bestechung, Duty-Free" },
    cn_west:        { name: "West Cigarettes",             qty: 1, weight: "0.03 kg", notes: "Deutsche Marke" },
    cn_hb:          { name: "HB Cigarettes",               qty: 1, weight: "0.03 kg", notes: "Old-School Deutsche Marke" },
    cn_cigar:       { name: "Cigar (single)",              qty: 1, weight: "0.02 kg", notes: "Mission-Success Ritual" },
    cn_pfeife:      { name: "Pfeifentabak (50 g)",         qty: 1, weight: "0.08 kg", notes: "Old-school deutsch" },
    cn_dip:         { name: "Dip Tin (Copenhagen)",        qty: 1, weight: "0.05 kg", notes: "Long-Op Vice, kein Geruch" },
    cn_nicgum:      { name: "Nicotine Gum",                qty: 1, weight: "0.01 kg", notes: "Substitut" },
    cn_zippo:       { name: "Zippo Lighter",               qty: 1, weight: "0.06 kg", notes: "Windproof, oft graviert" },
    cn_bic:         { name: "Bic Lighter",                 qty: 1, weight: "0.01 kg", notes: "Einweg, zuverlässig" },
    cn_matches:     { name: "Waterproof Matches",          qty: 1, weight: "0.02 kg", notes: "Survival-Backup" },
    cn_mre_heater:  { name: "MRE Flameless Heater",        qty: 1, weight: "0.03 kg", notes: "Wasseraktivierte exotherme Reaktion" },
    cn_hexamine:    { name: "Hexamine Tablet",             qty: 1, weight: "0.01 kg", notes: "Feststoff-Brennstoff, heizt Wasser ~10 min" },
    cn_esbit:       { name: "Esbit Folding Stove",         qty: 1, weight: "0.1 kg",  notes: "Taschenherd für Hex-Tabs" },
    cn_jetboil:     { name: "Jetboil Stove",               qty: 1, weight: "0.4 kg",  notes: "Integrierter Kanister-Herd, 0.5 L in ~100 s" },
    cn_jetboilcan:  { name: "Jetboil Canister (4 oz)",     qty: 1, weight: "0.2 kg",  notes: "Isobutan + Propan Mix" },
    cn_pocketrocket:{ name: "MSR PocketRocket",            qty: 1, weight: "0.07 kg", notes: "Minimalist Canister-Top Burner" },
    cn_jerrycan:    { name: "Jerry Can (20 L, empty)",     qty: 1, weight: "2.0 kg",  notes: "Stahl/Plastik Kraftstofftransport" },
    cn_petrol:      { name: "Petrol / Gasoline (1 L)",     qty: 1, weight: "0.75 kg", notes: "Bleifrei" },
    cn_diesel:      { name: "Diesel (1 L)",                qty: 1, weight: "0.85 kg", notes: "Fahrzeug/Generator-Kraftstoff" },
    cn_kerosene:    { name: "Kerosene (0.5 L)",            qty: 1, weight: "0.45 kg", notes: "Laternen, Heizer, kleine Öfen" },
    cn_propane:     { name: "Propane Canister (227g)",     qty: 1, weight: "0.5 kg",  notes: "Kleine Flasche, Öfen/Brenner" },
    cn_firestarter: { name: "Fire-Starter Cubes (20)",     qty: 1, weight: "0.08 kg", notes: "Paraffin-Zunder, zündet nasses Holz" },
  };

  on("change:repeating_gear:ipreset", (info) => {
    const src = (info && info.sourceAttribute) || "";
    const match = /^(repeating_gear_[^_]+)_/i.exec(src);
    if (!match) return;
    const rowPrefix = match[1];
    getAttrs([src], (v) => {
      const key = v[src];
      if (!key || key === "custom") {
        setAttrs({
          [`${rowPrefix}_icustom`]: "1",
          [`${rowPrefix}_iname`]:   "",
          [`${rowPrefix}_iweight`]: "",
          [`${rowPrefix}_inotes`]:  "",
        });
        return;
      }
      const p = GEAR_PRESETS[key];
      if (!p) return;
      setAttrs({
        [`${rowPrefix}_icustom`]: "0",
        [`${rowPrefix}_iname`]:   p.name,
        [`${rowPrefix}_iqty`]:    p.qty,
        [`${rowPrefix}_iweight`]: p.weight,
        [`${rowPrefix}_inotes`]:  p.notes,
      });
    });
  });

